### ISSUE TITLE
Process completed with exit code 3.

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#138]
Hello @katydecorah, me again.

I recently tried to save a bunch of bookmarks that failed with the error: `Process completed with exit code 3.`

It appears to be an issue with the download of the thumbnail image:

Download the thumbnail image
```bash
1s
Run curl "" -o "img/"
  curl "" -o "img/"
  shell: /bin/bash -e {0}
  env:
    DateBookmarked: 2023-07-02
    BookmarkTitle: How Websites Die
curl: (3) URL rejected: No host part in the URL
Error: Process completed with exit code 3.
```

Examples:
- https://github.com/flamedfury/metadata-library/actions/runs/5374740190
- https://github.com/flamedfury/metadata-library/actions/runs/5374757711
- https://github.com/flamedfury/metadata-library/actions/runs/5434264241
- https://github.com/flamedfury/metadata-library/actions/runs/5448906481
- https://github.com/flamedfury/metadata-library/actions/runs/5572970504
- https://github.com/flamedfury/metadata-library/actions/runs/5640355345
- https://github.com/flamedfury/metadata-library/actions/runs/5826116073

**Comment by katydecorah** [comment]
@flamedfury Looks like some of these URLs don't have images, so they fail at that step. Try adding the following `if` statement to your workflow:

https://github.com/katydecorah/bookmark-action/blob/c39bd1ac8121a5d461a4fbb7ac3224fa161edfb8/.github/workflows/bookmarks.yml#L32-L34

This will skip the download step and prevent the build from failing when there is no image to download.

**Comment by flamedfury** [comment]
Thanks, have run back through most of them. I think they've successfully run. 

I'll have to go in and manually add some images for them.

This has given me a new idea...

**Comment by katydecorah** [comment]
Great! Closing here, please re-open if this didn't fix it :)
