### ISSUE TITLE
Feature Request: Add Archive Link

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#139]
Hi Katy :wave: 

I thought a great feature to add would be when a URL is bookmarked; the action could grab the latest archive link from the [Wayback Machine](https://wayback.archive.org/) and add it to the JSON. 

This would be useful for the types of pages that I bookmark that sometimes don't last the next 6-12 months on the Internet.

**Comment by katydecorah** [comment]
😍 ON IT!
