### ISSUE TITLE
URL rejected: No host part in the URL

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#150]
Hey Katy,

Is there any way that we can get around this error?

https://github.com/flamedfury/metadata-library/actions/runs/7178793959/job/19547671628

~fLaMEd

**Comment by katydecorah** [comment]
Hey hey! The problem here is that the meta tag for the OG image is not absolute and so it fails when attempting to download. I can look into if bookmark-action can evaluate if the image can be downloaded and skip it if not

**Comment by flamedfury** [comment]
Have I messed my configuration up somewhere? 

https://github.com/flamedfury/metadata-library/actions/runs/7236168216

```bash
Add bookmark
Error getting metadata for https://rknight.me/assets/ogi/please-expose-your-rss.png: Must scrape an HTML page
```
