### ISSUE TITLE
New Optional Field "Quote"

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#154]
Hello again; hope all is well.

I'm hoping that you might add a new optional field for a "quote". 

The way I want to use this action is to record a quote from a webpage I'm bookmarking alongside my note.

This way when I render my individual bookmark page, https://flamedfury.com/bookmarks/the-state-of-the-independent-web-2022-updated-2024/ I have the option to render `{{ bookmark.quote }}` in a `<blockquote>` element and my note in a standard `<p>`

Hope this makes sense :)

**Comment by katydecorah** [comment]
Oooh I like it! Maybe I can add a way that you can define additional properties as you need them.... I'll think on it :)

**Comment by katydecorah** [comment]
@flamedfury This is live in v6.4.0 :)

1. To the task inputs add `additional-properties`. The value is a comma delimited string with property key names.
2. Update your workflow's dispatch inputs to define the new properties using the same key name.

Check out this workflow as an example for how I added "rating" and "quote": https://github.com/katydecorah/bookmark-action/blob/main/.github/workflows/bookmarks-advanced.yml

**Comment by flamedfury** [comment]
Works great, thank you!

https://flamedfury.com/bookmarks/please-dont-force-me-to-log-in/

**Comment by katydecorah** [comment]
Looks so rad!
