### ISSUE TITLE
Time support with the date property

### ISSUE THREAD

**Issue by flamedfury** [katydecorah/bookmark-action#158]
Hello Katy, me again :)

Would it be possible to add in a time stamp from when the action saves the bookmark to the JSON file? e.g. `date: 2024-04-05T20:07:30Z` 

This would help when I save multiple bookmarks per day, when they're posted to the RSS feed they all currently have the time `00:00`.

**Comment by katydecorah** [comment]
Sure thing! Here's what I'd like to propose @flamedfury:

1. Add new `timestamp` property where the value is an ISO string. Example: 
`"timestamp": "2024-04-06T17:30:00.000Z",`
2. Update bookmarks already in the JSON file by checking if they have `timestamp` if not, add one based on the `date`.  Example:
```json
{
    "date": "2021-01-03",
    "site": "NYT Cooking",
    "timestamp": "2021-01-03T00:00:00.000Z", // Time is blank for previous bookmarks as we don't know, but at least gives us a consistent format
    "title": "Cornmeal Lime Shortbread Fans Recipe",
    "url": "https://cooking.nytimes.com/recipes/1021663-cornmeal-lime-shortbread-fans",
  }
``` 
3. The `date` property remains the same (we could deprecate in the future, but I'm not too worried about it).

This helps prevent breaking anyone's current implementation of `date` and anyone who wants to start using the iso string can update their implementations to swap `date` with `timestamp`.

What do you think?

**Comment by flamedfury** [comment]
@katydecorah this sounds wonderful, I can work with this

**Comment by katydecorah** [comment]
Released in v7.0.0!

**Comment by flamedfury** [comment]
Works a treat 🎉 

![image](https://github.com/katydecorah/bookmark-action/assets/4757066/a1eb1ef9-63e2-4dab-9cc0-022bf25316ef)

Thanks again :)

**Comment by katydecorah** [comment]
So cool 🤩
